name: Trigger ADO Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Azure DevOps Pipeline
        env:
          ADO_PAT: ${{ secrets.ADO_PAT }}
          ADO_ORG: "UnipharGroup"
          ADO_PROJECT: "DAWN-dev"          
        run: |
          # Set variables
          ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workItems/34424/comments?api-version=7.1-preview.3"          
          # Trigger the pipeline
          response=$(curl -X GET "$ADO_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n ":${ADO_PAT}" | base64)" \
            -d '{ "text" = "Code Updated"  }')
          echo " response : $response "
                    
