name: Trigger ADO Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Azure DevOps Pipeline
        env:
          ADO_PAT: ${{ secrets.ADO_PAT }}
          ADO_ORG: "UnipharGroup"
          ADO_PROJECT: "DAWN-dev"              
        run: |
          # Set variables
          ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workItems/34424/comments?api-version=7.1-preview.3"          
          # Trigger the pipeline
          # JSON data to be sent
          json_data='{"text": "Code Updated hehhe1"}'
          encoded_pat=$(echo -n ":${PAT}" | base64)
          echo " pat : $encoded_pat"
          encoded_pat1=$(echo -n ":${ADO_PAT}" | base64)
          echo " secret pat : $encoded_pat1"          

          encoded_pat2=$(echo -n ":${encoded_pat}" | base64)
          echo " encode ka encode : $encoded_pat2"

          decoded_value=$(echo "$encoded_pat1" | base64 --decode)
          echo "decoded secret = $decoded_value"
          
          # Make the API request and capture the response
          response=$(curl -X POST "$ADO_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic OnQ1YnplZmVmc3RiMzVrenRxcGN0bWFnemU2eGRsaXpvaWZoaml1N3ZmdXk3aGlvcTZoc2E=" \
            -d "$json_data" \
            -w "%{http_code}" -o response_body.txt -s)
                    
          # Output HTTP status code and response body
          echo "HTTP Status Code: ${response}"
          echo "Response Body:"
          cat response_body.txt
