name: Trigger ADO Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Azure DevOps Pipeline
        env:
          ADO_PAT: ${{ secrets.ADO_PAT }}
        run: |
          # Set variables
          ADO_ORG="UnipharGroup"
          ADO_PROJECT="DAWN-dev"
          ADO_PIPELINE_ID="your_pipeline_id"
          ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workitems/34424?api-version=6.0"
          echo ${ADO_PAT}
          # Trigger pipeline
          # curl -X POST -H "Content-Type: application/json" -H "Authorization: Basic $(echo -n ":${ADO_PAT}" | base64)" ${ADO_URL}

          curl -X PATCH \
          -H "Authorization: Basic $(echo -n ":ADO_PAT" | base64)" \
          -H "Content-Type: application/json-patch+json" \
          -d '[{"op": "add", "path": "/fields/System.History", "value": "Code Updated."}]' \
          ${ADO_URL}
