name: Trigger ADO Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Azure DevOps Pipeline
        env:
          ADO_PAT: ${{ secrets.ADO_PAT }}
          username: ${{ secrets.USERNAME }}
        run: |
          # Set variables
          ADO_ORG="UnipharGroup"
          ADO_PROJECT="DAWN-dev"
          ADO_PIPELINE_ID="your_pipeline_id"
          #ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workitems/34424?api-version=6.0"
          ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workItems/34424/comments?api-version=7.1-preview.3"
  
          
          pat="${{ secrets.ADO_PAT }}"
          echo "pat value : $pat"
          username="${{ secrets.USERNAME }}"
          echo "usernamw is : $username"
          credpair="${username}:${pat}"          
                       
          echo " url is : $ADO_URL"          

          tokenHeaders=@{
              "Content-Type" = "application/x-www-form-urlencoded"
              "Authorization" = "Basic $pat"
          }
          echo "token : $tokenHeaders"
          tokenResponse=Invoke-RestMethod -Uri $ADO_URL -Method Patch -Body "grant_type=client_credentials" -Headers $tokenHeaders
          #Write-Output "Token: $(tokenResponse.access_token)"
          echo "tokenResponse is $tokenResponse "
