name: Trigger ADO Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Azure DevOps Pipeline
        env:
          ADO_PAT: ${{ secrets.ADO_PAT }}
          username: ${{ secrets.USERNAME }}
        run: |
          # Set variables
          ADO_ORG="UnipharGroup"
          ADO_PROJECT="DAWN-dev"
          ADO_PIPELINE_ID="your_pipeline_id"
          #ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workitems/34424?api-version=6.0"
          ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workItems/34424/comments?api-version=7.1-preview.3"
  
          
          pat="${{ secrets.ADO_PAT }}"
          echo "pat value : $pat"
          username="${{ secrets.USERNAME }}"
          echo "usernamw is : $username"
          credpair="${username}:${pat}"
          echo "credentails pair : $credpair"

          #encodedCredentials=[System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credpair))
          encodedCredentials=$(echo -n "$credpair" | base64)
          #echo "encodedCredentials : $encodedCredentials"
          #headers= @{'Content-Type' = "application/json-patch+json"
          #              'Accept' = "application/json; api-version=7.0"
          #              'Authorization' = "Basic $encodedCredentials"
          #             }
                       
          echo " url is : $ADO_URL"
          
          response=$(curl -s -X PATCH \
          -H "Authorization: Basic $(echo -n "3wmr4hqqjcbcp2n2zus7ejqgtksahfaisajpquo4uxko2sv7ftqq" )" \
          -H "Content-Type: application/json-patch+json" \
          -d '[{"op": "add", "path": "/fields/System.History", "value": "Code Updated."}]' \
          ${ADO_URL} )

          echo "response is ${response}"
          
          #$encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credPair))          
          # Trigger pipeline
          # curl -X POST -H "Content-Type: application/json" -H "Authorization: Basic $(echo -n ":${credPair}" | base64)" ${ADO_URL}

          #curl -X PATCH \
          #-H "Authorization: Basic $(echo -n ":encodedCredentials" | base64)" \
          #-H "Content-Type: application/json-patch+json" \
          #-d '[{"op": "add", "path": "/fields/System.History", "value": "Code Updated."}]' \
          #${ADO_URL}
