name: Trigger ADO Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Azure DevOps Pipeline
        env:
          ADO_PAT: ${{ secrets.ADO_PAT }}
          username: ${{ secrets.USERNAME }}
        run: |
          # Set variables
          ADO_ORG="UnipharGroup"
          ADO_PROJECT="DAWN-dev"
          ADO_PIPELINE_ID="your_pipeline_id"
          ADO_URL="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workitems/34424?api-version=6.0"

          pat="${{ secrets.ADO_PAT }}"
          echo "pat value : $pat"
          username="${{ secrets.USERNAME }}"
          echo "usernamw is : $username"
          credpair="${username}:${pat}"
          echo "credentails pair : $credpair"


          apiUrl="https://dev.azure.com/${ADO_ORG}/${ADO_PROJECT}/_apis/wit/workitems/34424?api-version=6.0"
          #encodedCredentials=[System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes${credpair})
          headers= @{'Content-Type' = "application/json-patch+json"
                        'Accept' = "application/json; api-version=7.0"
                        'Authorization' = "Basic $credpair"
                       }
          response=Invoke-RestMethod $apiUrl -Method GET -Headers $headers
          response1=$response | ConvertTo-Json
          echo "response : $response"

          curl -X PATCH \
          -H "Authorization: Basic $(echo -n ":credpair" | base64)" \
          -H "Content-Type: application/json-patch+json" \
          -d '[{"op": "add", "path": "/fields/System.History", "value": "Code Updated."}]' \
          ${ADO_URL}
          
          $encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credPair))          
          # Trigger pipeline
          # curl -X POST -H "Content-Type: application/json" -H "Authorization: Basic $(echo -n ":${credPair}" | base64)" ${ADO_URL}

          curl -X PATCH \
          -H "Authorization: Basic $(echo -n ":encodedCredentials" | base64)" \
          -H "Content-Type: application/json-patch+json" \
          -d '[{"op": "add", "path": "/fields/System.History", "value": "Code Updated."}]' \
          ${ADO_URL}
